spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/yycaa?serverTimezone=UTC
    username: root
    password: yycaa
    driver-class-name: com.mysql.cj.jdbc.Driver


  jdbc:
    template:
      query-timeout: 3

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/xml/mapper/CityMapper.xml
